
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS sales_count_text TEXT,
ADD COLUMN IF NOT EXISTS shipping_text TEXT,
ADD COLUMN IF NOT EXISTS shipping_timer_text TEXT,
ADD COLUMN IF NOT EXISTS stock_text TEXT,
ADD COLUMN IF NOT EXISTS trust_badge_1 TEXT,
ADD COLUMN IF NOT EXISTS trust_badge_2 TEXT,
ADD COLUMN IF NOT EXISTS trust_badge_3 TEXT;
